MAYOR -> Cambio de Sprint-Scrums a Scrom-Comeets
Soft-Coders/SIInt pull request #18
Opened 2022-03-21 18:04 UTC by martame18

@pablohud @iLopezosa @jesuscestino

2022-03-21 18:10 UTC, iLopezosa commented
OK

> Creo que habría que añadir lo de los periodos de entregas como Sprints y explicar que se divide en un periodo de preparación teórica y otro de desarrollo.

2022-03-21 18:14 UTC, iLopezosa requested changes
Linea 68: SCRUM -> Comeet

2022-03-21 18:23 UTC, jesuscestino reviewed
68 SCRUM -> Comeet

2022-03-21 20:44 UTC, iLopezosa commented
OK
> @pablohud aprueba y merge

2022-03-22 09:23 UTC, iLopezosa approved these changes

2022-03-22 10:14 UTC, merged