MAYOR -> Añadida especificación de etiquetas
Soft-Coders/SIInt pull request #28
Opened 2022-03-24 11:25 UTC by martame18

@jesuscestino @iLopezosa @pablohud

2022-03-24 12:31 UTC, pablohud requested changes
Falta especificar #none

2022-03-25 09:01 UTC, martame18 commented
> Falta especificar #none

Añadido

2022-03-25 19:45 UTC, iLopezosa approved these changes
OK

2022-03-26 11:42 UTC, pablohud approved these changes

2022-03-26 18:04 UTC, iLopezosa commented
@jesuscestino Approve and merge

2022-03-29 08:30 UTC, jesuscestino approved these changes
OK

2022-03-29 08:31 UTC, merged