MAJOR -> Maven en README
Soft-Coders/SIInt pull request #31
Opened 2022-03-27 00:38 UTC by martame18

@pablohud @iLopezosa @jesuscestino

2022-03-27 06:37 UTC, iLopezosa requested changes
No se específica la configuración o "modus operandi" a usar en Maven.

2022-03-27 06:38 UTC, iLopezosa commented
¿Maven antes de SCROM?

2022-03-27 09:15 UTC, pablohud commented
> ¿Maven antes de SCROM?

no sabíamos realme donde colocarlo, podemos ponerlo después si lo ves conveniente


> No se específica la configuración o "modus operandi" a usar en Maven.

En proceso

2022-03-27 15:26 UTC, iLopezosa commented
> no sabíamos realme donde colocarlo, podemos ponerlo después si lo ves conveniente
Pensad a qué le queréis dar más importancia, ya que será lo primero que se vea del repositorio.

> En proceso, le hemos preguntado dudas al profesor y lo especificamos en cuanto sepamos
De acuerdo. Yo dejaría esta rama unmerged hasta que se haya especificado, i.e. cerrar el PR o dejarlo abierto de forma indefinida.

2022-03-28 15:15 UTC, pablohud commented
> Pensad a qué le queréis dar más importancia, ya que será lo primero que se vea del repositorio.

Lo hemos cambiado a abajo del todo, ya que son tecnologías que usaremos todos y que no destaca nada en nuestro proyecto, por lo que vimos más conveniente ponerlo al fondo.

2022-03-28 15:17 UTC, pablohud approved these changes
OK

2022-03-28 15:19 UTC, iLopezosa approved these changes

2022-03-29 08:29 UTC, jesuscestino approved these changes
OK

2022-03-29 08:31 UTC, merged